### ISSUE TITLE
Make code citable

### ISSUE THREAD

**Issue by bauerfe** [synsense/sinabs-exodus#7]
See [here](https://guides.lib.berkeley.edu/citeyourcode) for details.

- [x] Add repo on [zenodo](https://zenodo.org/)
- [x] Include reference in README
- [x] Add GitHub citation file.

**Comment by sheiksadique** [comment]
FYI GitHub added native support for citations without having to go through zendo

**Comment by bauerfe** [comment]
Ah true, I forgot to include the citation file. Zenodo was mostly for getting a DOI.

**Comment by bauerfe** [comment]
Alright, I added the citation file. Please review @sheiksadique  (PR #9 )

**Comment by bauerfe** [comment]
This has already been merged. Closing.
